name: Publish Release

on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string
      is-pre-release:
        required: true
        type: boolean
    secrets:
      nuget-token:
        required: true

jobs:
  release:
    name: 📪 Release to GitHub
    if: ${{!inputs.is-pre-release}}
    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.100-rc.1.23463.5
      
      - name: Build
        shell: bash
        run: |
          release_name="bang-${{ inputs.release-version }}}-${{ matrix.target }}"

          # Build everything
          dotnet publish --runtime "${{ matrix.target }}" -c Release -o "$release_name" --no-self-contained

          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            # Pack to zip for Windows
            7z a -tzip "${release_name}.zip" "./${release_name}/*"
          else
            tar czvf "${release_name}.tar.gz" "$release_name"
          fi

          # Delete output directory
          rm -r "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "bang-release*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pack:
    name: 📦 Pack and publish to NuGet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.100-rc.1.23463.5

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
  
      - name: Pack and push
        run: |
            dotnet build -c Release
            dotnet pack -c Release /p:Version=${{inputs.release-version}}
            dotnet nuget push ./src/**/bin/Release/Murder.Bang.*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${nuget-token}
        env:
          nuget-token: ${{secrets.nuget-token}}
