name: Publish Release
on:
  release:
    types: [published]

jobs:
  generate-version-name:
    name: Generate version name
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.generate-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Calculate build version from Git
        id: generate-version
        run: |
          tag=$(git describe --tags --abbrev=0)
          echo "version=$version" >> "$GITHUB_OUTPUT"

  pre-release:
    name: Build for Linux
    needs: generate-version-name
    uses: ./.github/workflows/release.yaml
    with:
      release-version: ${{ needs.generate-version-name.outputs.version }}